# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    automerge: true
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - react*
      dev-dependencies:
        dependency-type: development
    allow:
      - dependency-type: "development"
    automerge: true
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin:
        patterns:
          - org.jetbrains.kotlin*
          - com.google.devtools.ksp
          - kotlinVersion
