micronaut:
  application:
    name: recipes
  server:
    cors:
      enabled: true
    multipart:
      max-file-size: 5000000
  router:
    static-resources:
      index:
        paths: "classpath:/public/index.html"
        mapping: "/"
      default:
        paths: "classpath:public"
        mapping: "/**"
  security:
    authentication: bearer
    token:
      enabled: true
      jwt:
        bearer:
          enabled: true
        generator:
          access-token:
            expiration: 60
          refresh-token:
            secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256
        enabled: true
    redirect:
      enabled: false
    endpoints:
      login:
        path: /api/login
      logout:
        enabled: false
      oauth:
        path: /api/token
        enabled: true
    intercept-url-map:
      - pattern: /api/login
        access:
          - isAnonymous()
      - pattern: /*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /static/**
        http-method: GET
        access:
          - isAnonymous()
    reject-not-found: true


logger:
    levels:
      io.micronaut: INFO
      de.w3is.recipes: DEBUG

application:
  initialAdminPassword: changeme
  allowInvitationFor: ADMIN,USER
  minPasswordLength: 5

jackson:
  serialization-inclusion: always