datasources:
  h2:
    url: jdbc:h2:./recipe.h2;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    sql-dialect: 'POSTGRES'

flyway:
  datasources:
    h2:
      enabled: true