micronaut:
  application:
    name: recipes
  server:
    cors:
      enabled: true
      configuration:
        web:
          allowedOrigins:
            - http://localhost:8080
            - http://127.0.0.1:8080
          allowedHeaders:
            - Content-Type
          allowedMethods:
            - POST
            - GET
            - OPTIONS
    multipart:
      max-file-size: 5000000
  router:
    static-resources:
      index:
        paths: "classpath:/public/index.html"
        mapping: "/"
      default:
        paths: "classpath:public"
        mapping: "/**"
  security:
    authentication: bearer
    token:
      enabled: true
      jwt:
        bearer:
          enabled: true
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256
        enabled: true
    redirect:
      enabled: false
    endpoints:
      login:
        path: /api/login
      logout:
        enabled: false
    intercept-url-map:
      - pattern: /api/login
        access:
          - isAnonymous()
      - pattern: /*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /static/**
        http-method: GET
        access:
          - isAnonymous()
    reject-not-found: true


logger:
    levels:
      io.micronaut: INFO
      de.w3is.recipes: DEBUG

application:
  initialAdminPassword: changeme
  allowInvitationFor: ADMIN,USER
  minPasswordLength: 5

jackson:
  serialization-inclusion: always