ALTER TABLE recipes ALTER COLUMN category SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN cuisine SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN yields SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN ingredients SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN instructions SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN modifications SET NOT NULL;
ALTER TABLE recipes ALTER COLUMN images SET NOT NULL;

