name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1.2.1
      with:
        node-version: 'v16.13.1'
        flags: '--cwd ./src/main/js/'
    - name: yarn build
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: '--cwd ./src/main/js/ run build'
    - name: Build Backend
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: clean build
