name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-releaes:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/setup-node@v2
        with:
          node-version: 'v16.13.1'
          cache: 'yarn'
          cache-dependency-path: './src/main/js/yarn.lock'
      - name: Install dependencies
        run: yarn --cwd ./src/main/js/ install --immutable
        shell: bash
      - name: yarn build
        run: yarn --cwd ./src/main/js/ run build
        shell: bash
      - name: Build Backend
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: clean build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            build/libs/recipes-0.1.jar
