name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tagged-releaes:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Build
        run: ./gradlew clean build
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            build/libs/recipes-1.0-all.jar
